version: "3.0"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOSTNAME: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
#    ports:
#      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql

  swagger:
    # docker run -d -p 80:8080 -e SWAGGER_JSON=/app/shop-api.yml -v .:/app swaggerapi/swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /app/shop-api.yml
      CORS: true

    volumes:
      - ./api/swagger:/app
    ports:
      - "8001:8080"
    depends_on:
      - app

volumes:
  database:
