# Generated by Django 4.2.7 on 2023-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='NW', max_length=2),
        ),
    ]
