# Generated by Django 5.0.1 on 2024-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_product_price_orderentry_profile_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN', 'Initial'), ('CO', 'Completed'), ('DE', 'Delivered')], default='IN', max_length=2),
        ),
    ]
